language: objective-c

before_install:
- brew update
- if brew outdated | grep -qx xctool; then brew upgrade xctool; fi

script:

- set -o pipefail && xcodebuild build -workspace Example/HKKit.xcworkspace -scheme HKKit -sdk iphonesimulator9.1 ONLY_ACTIVE_ARCH=NO | xcpretty

- xcodebuild build -project CEMKit-Swift.xcodeproj -scheme CEMKit-Swift

- sdk iphonesimulator9.1 ONLY_ACTIVE_ARCH=NO clean build | xcpretty
