language: objective-c

before_install:
- brew update
- if brew outdated | grep -qx xctool; then brew upgrade xctool; fi

script:

- xcodebuild build -project CEMKit-Swift.xcodeproj -scheme CEMKit-Swift

- sdk iphonesimulator9.1 ONLY_ACTIVE_ARCH=NO clean build | xcpretty
